### ISSUE TITLE
Fails for sizes greater than 28

### ISSUE THREAD

**Issue by eugen-vusak** [littlevgl/lv_font_conv#16]
Hi,

I wanted to convert font [Titillium Web](https://fonts.google.com/specimen/Titillium+Web?selection.family=Titillium+Web) of size 33  with range 0x20 - 0x17F and it failed. I noticed that it works for sizes <= 28. 
Next i tried using converter offline so I installed it and called 
`lv_font_conv --font Titillium_Web/TitilliumWeb-Regular.ttf --r 0x20-0x17F --bpp 4 --size 33 --format lvgl -o titillium_33.c`

Command failed as before. 
This is an output
```
/usr/lib/node_modules/lv_font_conv/lv_font_conv.js:17
  throw err;
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -148
    at writeU_Int8 (internal/buffer.js:572:11)
    at Buffer.writeInt8 (internal/buffer.js:703:10)
    at LvKern.create_format0_data (/usr/lib/node_modules/lv_font_conv/lib/font/table_kern.js:74:18)
    at LvKern.should_use_format3 (/usr/lib/node_modules/lv_font_conv/lib/font/table_kern.js:211:31)
    at LvKern.toLVGL (/usr/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_table_kern.js:105:16)
    at LvFont.toLVGL (/usr/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_font.js:55:13)
    at Object.write_images [as lvgl] (/usr/lib/node_modules/lv_font_conv/lib/writers/lvgl/index.js:15:25)
    at convert (/usr/lib/node_modules/lv_font_conv/lib/convert.js:26:35)
    at Object.module.exports.run (/usr/lib/node_modules/lv_font_conv/lib/cli.js:303:15)
    at Object.<anonymous> (/usr/lib/node_modules/lv_font_conv/lv_font_conv.js:8:24)
```

When I try with size 28 it does everything as expected. But with 29 it fails for same reason. 
Thanks in advance

**Comment by puzrin** [comment]
Reproduced with more narrow range:

```
 ./lv_font_conv.js --font TitilliumWeb-Regular.ttf --r 0x2F-0x41 --bpp 4 --size 33 --format bin -o titillium_33.c
/home/vitaly/Coding/lv_font_conv/lv_font_conv.js:17
  throw err;
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -148
    at writeU_Int8 (internal/buffer.js:555:11)
    at Buffer.writeInt8 (internal/buffer.js:686:10)
    at Kern.create_format0_data (/home/vitaly/Coding/lv_font_conv/lib/font/table_kern.js:74:18)
    at Kern.toBin (/home/vitaly/Coding/lv_font_conv/lib/font/table_kern.js:227:31)
    at Font.toBin (/home/vitaly/Coding/lv_font_conv/lib/font/font.js:121:17)
    at Object.write_images [as bin] (/home/vitaly/Coding/lv_font_conv/lib/writers/bin.js:15:25)
    at convert (/home/vitaly/Coding/lv_font_conv/lib/convert.js:26:35)
    at Object.module.exports.run (/home/vitaly/Coding/lv_font_conv/lib/cli.js:303:15)
    at Object.<anonymous> (/home/vitaly/Coding/lv_font_conv/lv_font_conv.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

Something minor... Thanks for report.

**Comment by puzrin** [comment]
Try now
